import Title from "@/components/title/Title";

export const metadata = {
	title: "Main",
	description: "Generated by create next app",
};

export default function Main() {
	return <Title someTitle="Main" />;
}
